DROP DATABASE IF EXISTS employees;
CREATE DATABASE emploees;

USE employees;


CREATE TABLE department (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE ROLL (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(250) UNIQUE NOT NULL,
    salary DECIMAL UNSIGNED NOT NULL,
    deapartment_id INT UNSIGNED NOT NULL,
    FOREIGN KEY(department_id)
    REFERENCES department(id)
);

CREATE TABLE employeee (
    id INT UNSIGNED AUTO_INCEMENT PRIMARY KEY,
    first_name VARCHAR(250) UNIQUE NOT NULL,
    last_name VARCHAR(250) UNIQUE NOT NULL,
    role_id INT UNSIGNED NOT NULL,
    FOREIGN KEY(role_id)
    REFERENCES role(id)
);